-- login_schema.sql
-- 目的: ログイン機能の Oracle 19c SE2 向けスキーマ定義（小規模プロダクト向け）
-- 反映方針: マイグレーションツールは使わず、レビュー後に手動で適用する
-- 前提: AL32UTF8 / UTC 運用 / Oracle Database 19c Standard Edition 2
-- 注意: Partitioning, In-Memory, Advanced Compression など EE 機能は使用しない
--------------------------------------------------------------------------------
-- users
--------------------------------------------------------------------------------
CREATE TABLE template_app.users (
  user_id                  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email                    VARCHAR2(255 CHAR) NOT NULL,
  password_hash            VARCHAR2(72 CHAR) NOT NULL,
  name                     VARCHAR2(100 CHAR) NOT NULL,
  role                     VARCHAR2(20 CHAR) DEFAULT 'ROLE_USER' NOT NULL,
  enabled                  NUMBER(1) DEFAULT 1 NOT NULL,
  failed_login_count       NUMBER(3) DEFAULT 0 NOT NULL,
  locked_until             TIMESTAMP(6),
  last_login_at            TIMESTAMP(6),
  last_password_changed_at TIMESTAMP(6) NOT NULL,
  version                  NUMBER(19) DEFAULT 0 NOT NULL,
  created_at               TIMESTAMP(6) NOT NULL,
  updated_at               TIMESTAMP(6) NOT NULL,
  CONSTRAINT uk_users_email UNIQUE (email)
) TABLESPACE TEMPLATE_TABLE;

--------------------------------------------------------------------------------
-- refresh_tokens
--------------------------------------------------------------------------------
CREATE TABLE template_app.refresh_tokens (
  token_id     NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      NUMBER(19) NOT NULL,
  token_hash   VARCHAR2(64 CHAR) NOT NULL,
  issued_at    TIMESTAMP(6) NOT NULL,
  expires_at   TIMESTAMP(6) NOT NULL,
  revoked_at   TIMESTAMP(6),
  user_agent   VARCHAR2(512 CHAR),
  ip_address   VARCHAR2(64 CHAR),
  CONSTRAINT uk_refresh_tokens_token_hash UNIQUE (token_hash)
) TABLESPACE TEMPLATE_TABLE;

--------------------------------------------------------------------------------
-- login_attempts
--------------------------------------------------------------------------------
CREATE TABLE template_app.login_attempts (
  attempt_id      NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         NUMBER(19),
  email           VARCHAR2(255 CHAR) NOT NULL,
  succeeded       NUMBER(1) NOT NULL,
  failure_reason  VARCHAR2(30 CHAR),
  ip_address      VARCHAR2(64 CHAR),
  attempted_at    TIMESTAMP(6) NOT NULL
) TABLESPACE TEMPLATE_TABLE;

--------------------------------------------------------------------------------
-- password_reset_tokens
--------------------------------------------------------------------------------
CREATE TABLE template_app.password_reset_tokens (
  token_id       NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        NUMBER(19) NOT NULL,
  token_hash     VARCHAR2(64 CHAR) NOT NULL,
  expires_at     TIMESTAMP(6) NOT NULL,
  used_at        TIMESTAMP(6),
  created_at     TIMESTAMP(6) NOT NULL,
  requester_ip   VARCHAR2(64 CHAR),
  CONSTRAINT uk_password_reset_token_hash UNIQUE (token_hash)
) TABLESPACE TEMPLATE_TABLE;

--------------------------------------------------------------------------------
-- indexes
--------------------------------------------------------------------------------
CREATE INDEX idx_refresh_tokens_user_revoked
  ON template_app.refresh_tokens (user_id, revoked_at)
  TABLESPACE TEMPLATE_INDEX;

CREATE INDEX idx_refresh_tokens_expires_at
  ON template_app.refresh_tokens (expires_at)
  TABLESPACE TEMPLATE_INDEX;

CREATE INDEX idx_login_attempts_email_attempted
  ON template_app.login_attempts (email, attempted_at)
  TABLESPACE TEMPLATE_INDEX;

CREATE INDEX idx_login_attempts_attempted_at
  ON template_app.login_attempts (attempted_at)
  TABLESPACE TEMPLATE_INDEX;

CREATE INDEX idx_password_reset_tokens_user_expires
  ON template_app.password_reset_tokens (user_id, expires_at)
  TABLESPACE TEMPLATE_INDEX;
