/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.12.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.kizunavi.controller;

import com.kizunavi.dto.ErrorResponse;
import com.kizunavi.dto.FirstLoginRequest;
import com.kizunavi.dto.ForgotPasswordRequest;
import com.kizunavi.dto.LoginRequest;
import com.kizunavi.dto.LoginResponse;
import com.kizunavi.dto.PasswordResetVerifyResponse;
import com.kizunavi.dto.ResetPasswordRequest;
import com.kizunavi.dto.SimpleStatusResponse;
import com.kizunavi.dto.StatusMessage;
import com.kizunavi.dto.TokenRefreshResponse;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.12.0")
@Validated
@Tag(name = "auth", description = "認証・パスワード管理")
public interface AuthApi {

    /**
     * PUT /api/auth/firstlogin : 初回パスワード設定
     * 仮パスワードを検証し、新しいパスワードを設定する。 【前提】本APIはtempPassword（仮パスワード）をRequest Bodyに含むため、HTTPS必須。HTTP通信は許可しないこと。 
     *
     * @param firstLoginRequest  (required)
     * @return パスワード設定成功 (status code 200)
     *         or 認証エラー（トークン未指定・無効・期限切れ） (status code 401)
     */
    @Operation(
        operationId = "firstLogin",
        summary = "初回パスワード設定",
        description = "仮パスワードを検証し、新しいパスワードを設定する。 【前提】本APIはtempPassword（仮パスワード）をRequest Bodyに含むため、HTTPS必須。HTTP通信は許可しないこと。 ",
        tags = { "auth" },
        responses = {
            @ApiResponse(responseCode = "200", description = "パスワード設定成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SimpleStatusResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "認証エラー（トークン未指定・無効・期限切れ）", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/api/auth/firstlogin",
        produces = { "application/json" },
        consumes = "application/json"
    )
    
    ResponseEntity<SimpleStatusResponse> firstLogin(
        @Parameter(name = "FirstLoginRequest", description = "", required = true) @Valid @RequestBody FirstLoginRequest firstLoginRequest
    );


    /**
     * POST /api/auth/password/forgot : パスワード再発行メール送信
     * 指定メールアドレス宛にパスワードリセット用URLを送信する。 セキュリティのため、メールアドレスが存在しない場合も同じレスポンスを返す。 
     *
     * @param forgotPasswordRequest  (required)
     * @return 送信完了（メールアドレス不存在の場合も同じレスポンス） (status code 200)
     */
    @Operation(
        operationId = "forgotPassword",
        summary = "パスワード再発行メール送信",
        description = "指定メールアドレス宛にパスワードリセット用URLを送信する。 セキュリティのため、メールアドレスが存在しない場合も同じレスポンスを返す。 ",
        tags = { "auth" },
        responses = {
            @ApiResponse(responseCode = "200", description = "送信完了（メールアドレス不存在の場合も同じレスポンス）", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SimpleStatusResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/auth/password/forgot",
        produces = { "application/json" },
        consumes = "application/json"
    )
    
    ResponseEntity<SimpleStatusResponse> forgotPassword(
        @Parameter(name = "ForgotPasswordRequest", description = "", required = true) @Valid @RequestBody ForgotPasswordRequest forgotPasswordRequest
    );


    /**
     * POST /api/auth/login : ログイン
     * メールアドレスとパスワードで認証し、アクセストークンを取得する。
     *
     * @param loginRequest  (required)
     * @return ログイン成功 (status code 200)
     *         or 認証エラー（トークン未指定・無効・期限切れ） (status code 401)
     *         or アカウントロック中 (status code 423)
     */
    @Operation(
        operationId = "login",
        summary = "ログイン",
        description = "メールアドレスとパスワードで認証し、アクセストークンを取得する。",
        tags = { "auth" },
        responses = {
            @ApiResponse(responseCode = "200", description = "ログイン成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = LoginResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "認証エラー（トークン未指定・無効・期限切れ）", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "423", description = "アカウントロック中", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/auth/login",
        produces = { "application/json" },
        consumes = "application/json"
    )
    
    ResponseEntity<LoginResponse> login(
        @Parameter(name = "LoginRequest", description = "", required = true) @Valid @RequestBody LoginRequest loginRequest
    );


    /**
     * POST /api/auth/logout : ログアウト
     * リフレッシュトークンを失効させる。アクセストークンはステートレスのためサーバー側での無効化は不要。
     *
     * @param refreshToken リフレッシュトークン（HttpOnly Cookieとしてブラウザが自動送信） (required)
     * @return ログアウト成功 (status code 200)
     *         or 認証エラー（トークン未指定・無効・期限切れ） (status code 401)
     */
    @Operation(
        operationId = "logout",
        summary = "ログアウト",
        description = "リフレッシュトークンを失効させる。アクセストークンはステートレスのためサーバー側での無効化は不要。",
        tags = { "auth" },
        responses = {
            @ApiResponse(responseCode = "200", description = "ログアウト成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = StatusMessage.class))
            }),
            @ApiResponse(responseCode = "401", description = "認証エラー（トークン未指定・無効・期限切れ）", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/auth/logout",
        produces = { "application/json" }
    )
    
    ResponseEntity<StatusMessage> logout(
        @NotNull @Parameter(name = "refreshToken", description = "リフレッシュトークン（HttpOnly Cookieとしてブラウザが自動送信）", required = true, in = ParameterIn.COOKIE) @CookieValue(name = "refreshToken") String refreshToken
    );


    /**
     * POST /api/auth/refresh : トークンリフレッシュ
     * HttpOnly CookieのrefreshTokenを使って新しいアクセストークンを発行する。 refreshTokenはブラウザが自動送信するためリクエストボディへの指定は不要。 ローテーション処理により旧refreshTokenは失効し、新しいrefreshTokenがSet-Cookieで返される。 
     *
     * @param refreshToken リフレッシュトークン（HttpOnly Cookieとしてブラウザが自動送信） (required)
     * @return トークン発行成功 (status code 200)
     *         or 認証エラー（トークン未指定・無効・期限切れ） (status code 401)
     */
    @Operation(
        operationId = "refreshToken",
        summary = "トークンリフレッシュ",
        description = "HttpOnly CookieのrefreshTokenを使って新しいアクセストークンを発行する。 refreshTokenはブラウザが自動送信するためリクエストボディへの指定は不要。 ローテーション処理により旧refreshTokenは失効し、新しいrefreshTokenがSet-Cookieで返される。 ",
        tags = { "auth" },
        responses = {
            @ApiResponse(responseCode = "200", description = "トークン発行成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = TokenRefreshResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "認証エラー（トークン未指定・無効・期限切れ）", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/auth/refresh",
        produces = { "application/json" }
    )
    
    ResponseEntity<TokenRefreshResponse> refreshToken(
        @NotNull @Parameter(name = "refreshToken", description = "リフレッシュトークン（HttpOnly Cookieとしてブラウザが自動送信）", required = true, in = ParameterIn.COOKIE) @CookieValue(name = "refreshToken") String refreshToken
    );


    /**
     * PUT /api/auth/password/reset : パスワード再設定
     * トークンを検証し、新しいパスワードを設定する。
     *
     * @param resetPasswordRequest  (required)
     * @return パスワード更新成功 (status code 200)
     *         or リクエストパラメータ不正 (status code 400)
     *         or 認証エラー（トークン未指定・無効・期限切れ） (status code 401)
     */
    @Operation(
        operationId = "resetPassword",
        summary = "パスワード再設定",
        description = "トークンを検証し、新しいパスワードを設定する。",
        tags = { "auth" },
        responses = {
            @ApiResponse(responseCode = "200", description = "パスワード更新成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SimpleStatusResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "リクエストパラメータ不正", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "認証エラー（トークン未指定・無効・期限切れ）", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/api/auth/password/reset",
        produces = { "application/json" },
        consumes = "application/json"
    )
    
    ResponseEntity<SimpleStatusResponse> resetPassword(
        @Parameter(name = "ResetPasswordRequest", description = "", required = true) @Valid @RequestBody ResetPasswordRequest resetPasswordRequest
    );


    /**
     * GET /api/auth/password/reset/verify/{token} : パスワードリセットトークン検証
     * メールのリンククリック時に呼び出し、トークンの有効性を検証する。
     *
     * @param token リセットトークン（PASSWORD_RESET_TOKENS.tokenHashの元値） (required)
     * @return 検証結果 (status code 200)
     */
    @Operation(
        operationId = "verifyResetToken",
        summary = "パスワードリセットトークン検証",
        description = "メールのリンククリック時に呼び出し、トークンの有効性を検証する。",
        tags = { "auth" },
        responses = {
            @ApiResponse(responseCode = "200", description = "検証結果", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PasswordResetVerifyResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/auth/password/reset/verify/{token}",
        produces = { "application/json" }
    )
    
    ResponseEntity<PasswordResetVerifyResponse> verifyResetToken(
        @Parameter(name = "token", description = "リセットトークン（PASSWORD_RESET_TOKENS.tokenHashの元値）", required = true, in = ParameterIn.PATH) @PathVariable("token") String token
    );

}
