/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.12.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.kizunavi.controller;

import com.kizunavi.dto.DashboardListResponse;
import com.kizunavi.dto.DashboardResponse;
import com.kizunavi.dto.ErrorResponse;
import java.util.UUID;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.12.0")
@Validated
@Tag(name = "dashboard", description = "ダッシュボード")
public interface DashboardApi {

    /**
     * GET /api/dashboard/{surveyId} : ダッシュボード取得
     * 指定したsurveyIdのサーベイについて、サーベイ一覧・サマリー・従業員バリュー分布を一括取得する。 customerIdはJWTから取得するためクエリパラメータへの指定は不要。 ※レスポンスが大きい場合は将来的にAPIの分離を検討（2026/05/13） 
     *
     * @param surveyId サーベイID (required)
     * @return ダッシュボードデータ (status code 200)
     *         or 認証エラー（トークン未指定・無効・期限切れ） (status code 401)
     *         or リソースが存在しない (status code 404)
     */
    @Operation(
        operationId = "getDashboard",
        summary = "ダッシュボード取得",
        description = "指定したsurveyIdのサーベイについて、サーベイ一覧・サマリー・従業員バリュー分布を一括取得する。 customerIdはJWTから取得するためクエリパラメータへの指定は不要。 ※レスポンスが大きい場合は将来的にAPIの分離を検討（2026/05/13） ",
        tags = { "dashboard" },
        responses = {
            @ApiResponse(responseCode = "200", description = "ダッシュボードデータ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DashboardResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "認証エラー（トークン未指定・無効・期限切れ）", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "リソースが存在しない", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/dashboard/{surveyId}",
        produces = { "application/json" }
    )
    
    ResponseEntity<DashboardResponse> getDashboard(
        @Parameter(name = "surveyId", description = "サーベイID", required = true, in = ParameterIn.PATH) @PathVariable("surveyId") UUID surveyId
    );


    /**
     * GET /api/dashboard/list : サーベイ一覧取得
     * 全サーベイ一覧を取得する。サイドバー・ドロップダウンのサーベイ切替用。 customerIdはJWTから取得するためクエリパラメータへの指定は不要。 SURVEY_DETAILSをcustomerIdで絞り込み、createdAt降順で返却。 サーベイが0件の場合はsurveysを空配列で返す。 
     *
     * @return サーベイ一覧 (status code 200)
     *         or 認証エラー（トークン未指定・無効・期限切れ） (status code 401)
     */
    @Operation(
        operationId = "getDashboardList",
        summary = "サーベイ一覧取得",
        description = "全サーベイ一覧を取得する。サイドバー・ドロップダウンのサーベイ切替用。 customerIdはJWTから取得するためクエリパラメータへの指定は不要。 SURVEY_DETAILSをcustomerIdで絞り込み、createdAt降順で返却。 サーベイが0件の場合はsurveysを空配列で返す。 ",
        tags = { "dashboard" },
        responses = {
            @ApiResponse(responseCode = "200", description = "サーベイ一覧", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DashboardListResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "認証エラー（トークン未指定・無効・期限切れ）", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/dashboard/list",
        produces = { "application/json" }
    )
    
    ResponseEntity<DashboardListResponse> getDashboardList(
        
    );

}
