/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.12.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.kizunavi.controller;

import com.kizunavi.dto.CreateDivisionRequest;
import com.kizunavi.dto.CreateDivisionResponse;
import com.kizunavi.dto.CreateEmployeeRequest;
import com.kizunavi.dto.CreateEmployeeResponse;
import com.kizunavi.dto.CreateSectionRequest;
import com.kizunavi.dto.CreateSectionResponse;
import com.kizunavi.dto.DivisionListResponse;
import com.kizunavi.dto.EmployeeListResponse;
import com.kizunavi.dto.ErrorResponse;
import com.kizunavi.dto.RoleLabelListResponse;
import com.kizunavi.dto.SectionListResponse;
import com.kizunavi.dto.SimpleStatusResponse;
import com.kizunavi.dto.StatusMessage;
import java.util.UUID;
import com.kizunavi.dto.UpdateDivisionRequest;
import com.kizunavi.dto.UpdateEmployeeRequest;
import com.kizunavi.dto.UpdateRoleLabelRequest;
import com.kizunavi.dto.UpdateRoleLabelResponse;
import com.kizunavi.dto.UpdateSectionRequest;
import com.kizunavi.dto.UpdatedAtResponse;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.12.0")
@Validated
@Tag(name = "employees", description = "従業員登録画面（従業員・部門・課・役職）")
public interface EmployeesApi {

    /**
     * POST /api/divisions : 部門登録
     * displayOrder省略時は既存の最大displayOrder+1を設定。
     *
     * @param createDivisionRequest  (required)
     * @return 登録成功 (status code 201)
     *         or 認証エラー（トークン未指定・無効・期限切れ） (status code 401)
     */
    @Operation(
        operationId = "createDivision",
        summary = "部門登録",
        description = "displayOrder省略時は既存の最大displayOrder+1を設定。",
        tags = { "employees" },
        responses = {
            @ApiResponse(responseCode = "201", description = "登録成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CreateDivisionResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "認証エラー（トークン未指定・無効・期限切れ）", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/divisions",
        produces = { "application/json" },
        consumes = "application/json"
    )
    
    ResponseEntity<CreateDivisionResponse> createDivision(
        @Parameter(name = "CreateDivisionRequest", description = "", required = true) @Valid @RequestBody CreateDivisionRequest createDivisionRequest
    );


    /**
     * POST /api/employees : 従業員登録
     * EMPLOYEESとUSERSを同一トランザクションで登録する。 kizunaLevel&#x3D;2（役員）はdivisionId / sectionId&#x3D;NULLで登録。 登録完了後に仮パスワードをメールで従業員に送信。 
     *
     * @param createEmployeeRequest  (required)
     * @return 従業員登録成功 (status code 201)
     *         or 認証エラー（トークン未指定・無効・期限切れ） (status code 401)
     *         or メールアドレス重複 (status code 409)
     */
    @Operation(
        operationId = "createEmployee",
        summary = "従業員登録",
        description = "EMPLOYEESとUSERSを同一トランザクションで登録する。 kizunaLevel=2（役員）はdivisionId / sectionId=NULLで登録。 登録完了後に仮パスワードをメールで従業員に送信。 ",
        tags = { "employees" },
        responses = {
            @ApiResponse(responseCode = "201", description = "従業員登録成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CreateEmployeeResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "認証エラー（トークン未指定・無効・期限切れ）", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "メールアドレス重複", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/employees",
        produces = { "application/json" },
        consumes = "application/json"
    )
    
    ResponseEntity<CreateEmployeeResponse> createEmployee(
        @Parameter(name = "CreateEmployeeRequest", description = "", required = true) @Valid @RequestBody CreateEmployeeRequest createEmployeeRequest
    );


    /**
     * POST /api/sections : 課登録
     * divisionIdの存在確認を行い、存在しない場合は404エラー。
     *
     * @param createSectionRequest  (required)
     * @return 登録成功 (status code 201)
     *         or 認証エラー（トークン未指定・無効・期限切れ） (status code 401)
     *         or リソースが存在しない (status code 404)
     */
    @Operation(
        operationId = "createSection",
        summary = "課登録",
        description = "divisionIdの存在確認を行い、存在しない場合は404エラー。",
        tags = { "employees" },
        responses = {
            @ApiResponse(responseCode = "201", description = "登録成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CreateSectionResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "認証エラー（トークン未指定・無効・期限切れ）", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "リソースが存在しない", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/sections",
        produces = { "application/json" },
        consumes = "application/json"
    )
    
    ResponseEntity<CreateSectionResponse> createSection(
        @Parameter(name = "CreateSectionRequest", description = "", required = true) @Valid @RequestBody CreateSectionRequest createSectionRequest
    );


    /**
     * DELETE /api/divisions/{divisionId} : 部門削除（論理削除）
     * DIVISIONS.delFlg&#x3D;1に更新。 配下のSECTIONSも合わせてdelFlg&#x3D;1に更新。 該当divisionIdを持つEMPLOYEESのdivisionId&#x3D;NULLに更新。 
     *
     * @param divisionId 部ID（UUID） (required)
     * @return 削除成功 (status code 200)
     *         or 認証エラー（トークン未指定・無効・期限切れ） (status code 401)
     *         or リソースが存在しない (status code 404)
     */
    @Operation(
        operationId = "deleteDivision",
        summary = "部門削除（論理削除）",
        description = "DIVISIONS.delFlg=1に更新。 配下のSECTIONSも合わせてdelFlg=1に更新。 該当divisionIdを持つEMPLOYEESのdivisionId=NULLに更新。 ",
        tags = { "employees" },
        responses = {
            @ApiResponse(responseCode = "200", description = "削除成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SimpleStatusResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "認証エラー（トークン未指定・無効・期限切れ）", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "リソースが存在しない", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/api/divisions/{divisionId}",
        produces = { "application/json" }
    )
    
    ResponseEntity<SimpleStatusResponse> deleteDivision(
        @Parameter(name = "divisionId", description = "部ID（UUID）", required = true, in = ParameterIn.PATH) @PathVariable("divisionId") UUID divisionId
    );


    /**
     * DELETE /api/employees/{employeeId} : 従業員削除（論理削除）
     * USERS.enabled&#x3D;0に更新（論理削除）。EMPLOYEESは削除しない。 REFRESH_TOKENSの該当ユーザーの全行をrevokedAtに現在時刻をセット（強制ログアウト）。 
     *
     * @param employeeId 従業員ID（UUID） (required)
     * @return 削除成功 (status code 200)
     *         or 認証エラー（トークン未指定・無効・期限切れ） (status code 401)
     *         or リソースが存在しない (status code 404)
     */
    @Operation(
        operationId = "deleteEmployee",
        summary = "従業員削除（論理削除）",
        description = "USERS.enabled=0に更新（論理削除）。EMPLOYEESは削除しない。 REFRESH_TOKENSの該当ユーザーの全行をrevokedAtに現在時刻をセット（強制ログアウト）。 ",
        tags = { "employees" },
        responses = {
            @ApiResponse(responseCode = "200", description = "削除成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = StatusMessage.class))
            }),
            @ApiResponse(responseCode = "401", description = "認証エラー（トークン未指定・無効・期限切れ）", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "リソースが存在しない", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/api/employees/{employeeId}",
        produces = { "application/json" }
    )
    
    ResponseEntity<StatusMessage> deleteEmployee(
        @Parameter(name = "employeeId", description = "従業員ID（UUID）", required = true, in = ParameterIn.PATH) @PathVariable("employeeId") UUID employeeId
    );


    /**
     * DELETE /api/sections/{sectionId} : 課削除（論理削除）
     * SECTIONS.delFlg&#x3D;1に更新。 該当sectionIdを持つEMPLOYEESのsectionId&#x3D;NULLに更新。 
     *
     * @param sectionId 課ID（UUID） (required)
     * @return 削除成功 (status code 200)
     *         or 認証エラー（トークン未指定・無効・期限切れ） (status code 401)
     *         or リソースが存在しない (status code 404)
     */
    @Operation(
        operationId = "deleteSection",
        summary = "課削除（論理削除）",
        description = "SECTIONS.delFlg=1に更新。 該当sectionIdを持つEMPLOYEESのsectionId=NULLに更新。 ",
        tags = { "employees" },
        responses = {
            @ApiResponse(responseCode = "200", description = "削除成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SimpleStatusResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "認証エラー（トークン未指定・無効・期限切れ）", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "リソースが存在しない", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/api/sections/{sectionId}",
        produces = { "application/json" }
    )
    
    ResponseEntity<SimpleStatusResponse> deleteSection(
        @Parameter(name = "sectionId", description = "課ID（UUID）", required = true, in = ParameterIn.PATH) @PathVariable("sectionId") UUID sectionId
    );


    /**
     * GET /api/divisions : 部一覧取得
     * customerIdで絞り込み。delFlg&#x3D;0のみ・displayOrder昇順で返却。
     *
     * @return 部一覧 (status code 200)
     *         or 認証エラー（トークン未指定・無効・期限切れ） (status code 401)
     */
    @Operation(
        operationId = "getDivisions",
        summary = "部一覧取得",
        description = "customerIdで絞り込み。delFlg=0のみ・displayOrder昇順で返却。",
        tags = { "employees" },
        responses = {
            @ApiResponse(responseCode = "200", description = "部一覧", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DivisionListResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "認証エラー（トークン未指定・無効・期限切れ）", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/divisions",
        produces = { "application/json" }
    )
    
    ResponseEntity<DivisionListResponse> getDivisions(
        
    );


    /**
     * GET /api/employees : 従業員一覧取得
     * customerIdはJWTから取得。 USERS.enabled&#x3D;0（論理削除済み）の従業員は返さない。 
     *
     * @return 従業員一覧 (status code 200)
     *         or 認証エラー（トークン未指定・無効・期限切れ） (status code 401)
     */
    @Operation(
        operationId = "getEmployees",
        summary = "従業員一覧取得",
        description = "customerIdはJWTから取得。 USERS.enabled=0（論理削除済み）の従業員は返さない。 ",
        tags = { "employees" },
        responses = {
            @ApiResponse(responseCode = "200", description = "従業員一覧", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = EmployeeListResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "認証エラー（トークン未指定・無効・期限切れ）", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/employees",
        produces = { "application/json" }
    )
    
    ResponseEntity<EmployeeListResponse> getEmployees(
        
    );


    /**
     * GET /api/role-labels : 役職一覧取得
     * ROLE_LABEL_SETTINGSをcustomerIdで絞り込み。 レコードがないkizunaLevelはデフォルト名で補完（1&#x3D;社長 2&#x3D;役員 3&#x3D;部長 4&#x3D;課長 5&#x3D;社員）。 kizunaLevel昇順で返却。 
     *
     * @return 役職一覧 (status code 200)
     *         or 認証エラー（トークン未指定・無効・期限切れ） (status code 401)
     */
    @Operation(
        operationId = "getRoleLabels",
        summary = "役職一覧取得",
        description = "ROLE_LABEL_SETTINGSをcustomerIdで絞り込み。 レコードがないkizunaLevelはデフォルト名で補完（1=社長 2=役員 3=部長 4=課長 5=社員）。 kizunaLevel昇順で返却。 ",
        tags = { "employees" },
        responses = {
            @ApiResponse(responseCode = "200", description = "役職一覧", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = RoleLabelListResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "認証エラー（トークン未指定・無効・期限切れ）", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/role-labels",
        produces = { "application/json" }
    )
    
    ResponseEntity<RoleLabelListResponse> getRoleLabels(
        
    );


    /**
     * GET /api/sections : 課一覧取得
     * divisionId指定時はその部の課のみ返す。delFlg&#x3D;0・displayOrder昇順。
     *
     * @param divisionId 部ID（省略時は全課） (optional)
     * @return 課一覧 (status code 200)
     *         or 認証エラー（トークン未指定・無効・期限切れ） (status code 401)
     */
    @Operation(
        operationId = "getSections",
        summary = "課一覧取得",
        description = "divisionId指定時はその部の課のみ返す。delFlg=0・displayOrder昇順。",
        tags = { "employees" },
        responses = {
            @ApiResponse(responseCode = "200", description = "課一覧", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SectionListResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "認証エラー（トークン未指定・無効・期限切れ）", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/sections",
        produces = { "application/json" }
    )
    
    ResponseEntity<SectionListResponse> getSections(
        @Parameter(name = "divisionId", description = "部ID（省略時は全課）", in = ParameterIn.QUERY) @Valid @RequestParam(value = "divisionId", required = false) UUID divisionId
    );


    /**
     * PUT /api/divisions/{divisionId} : 部門情報更新
     *
     * @param divisionId 部ID（UUID） (required)
     * @param updateDivisionRequest  (required)
     * @return 更新成功 (status code 200)
     *         or 認証エラー（トークン未指定・無効・期限切れ） (status code 401)
     *         or リソースが存在しない (status code 404)
     */
    @Operation(
        operationId = "updateDivision",
        summary = "部門情報更新",
        tags = { "employees" },
        responses = {
            @ApiResponse(responseCode = "200", description = "更新成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UpdatedAtResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "認証エラー（トークン未指定・無効・期限切れ）", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "リソースが存在しない", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/api/divisions/{divisionId}",
        produces = { "application/json" },
        consumes = "application/json"
    )
    
    ResponseEntity<UpdatedAtResponse> updateDivision(
        @Parameter(name = "divisionId", description = "部ID（UUID）", required = true, in = ParameterIn.PATH) @PathVariable("divisionId") UUID divisionId,
        @Parameter(name = "UpdateDivisionRequest", description = "", required = true) @Valid @RequestBody UpdateDivisionRequest updateDivisionRequest
    );


    /**
     * PUT /api/employees/{employeeId} : 従業員情報更新
     * EMPLOYEESとUSERSを同一トランザクションで更新。 employeeId + customerIdで対象を特定。 kizunaLevel&#x3D;2に変更する場合はdivisionId / sectionId&#x3D;NULLにセット。 
     *
     * @param employeeId 従業員ID（UUID） (required)
     * @param updateEmployeeRequest  (required)
     * @return 更新成功 (status code 200)
     *         or 認証エラー（トークン未指定・無効・期限切れ） (status code 401)
     *         or リソースが存在しない (status code 404)
     */
    @Operation(
        operationId = "updateEmployee",
        summary = "従業員情報更新",
        description = "EMPLOYEESとUSERSを同一トランザクションで更新。 employeeId + customerIdで対象を特定。 kizunaLevel=2に変更する場合はdivisionId / sectionId=NULLにセット。 ",
        tags = { "employees" },
        responses = {
            @ApiResponse(responseCode = "200", description = "更新成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UpdatedAtResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "認証エラー（トークン未指定・無効・期限切れ）", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "リソースが存在しない", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/api/employees/{employeeId}",
        produces = { "application/json" },
        consumes = "application/json"
    )
    
    ResponseEntity<UpdatedAtResponse> updateEmployee(
        @Parameter(name = "employeeId", description = "従業員ID（UUID）", required = true, in = ParameterIn.PATH) @PathVariable("employeeId") UUID employeeId,
        @Parameter(name = "UpdateEmployeeRequest", description = "", required = true) @Valid @RequestBody UpdateEmployeeRequest updateEmployeeRequest
    );


    /**
     * PUT /api/role-labels/{kizunaLevel} : 役職情報更新（UPSERT）
     * レコードがある場合はUPDATE、ない場合はINSERT（UPSERT）。kizunaLevelは1〜5のみ許可。
     *
     * @param kizunaLevel 役職レベル（1〜5） (required)
     * @param updateRoleLabelRequest  (required)
     * @return 更新成功 (status code 200)
     *         or リクエストパラメータ不正 (status code 400)
     *         or 認証エラー（トークン未指定・無効・期限切れ） (status code 401)
     */
    @Operation(
        operationId = "updateRoleLabel",
        summary = "役職情報更新（UPSERT）",
        description = "レコードがある場合はUPDATE、ない場合はINSERT（UPSERT）。kizunaLevelは1〜5のみ許可。",
        tags = { "employees" },
        responses = {
            @ApiResponse(responseCode = "200", description = "更新成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UpdateRoleLabelResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "リクエストパラメータ不正", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "認証エラー（トークン未指定・無効・期限切れ）", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/api/role-labels/{kizunaLevel}",
        produces = { "application/json" },
        consumes = "application/json"
    )
    
    ResponseEntity<UpdateRoleLabelResponse> updateRoleLabel(
        @Min(1) @Max(5) @Parameter(name = "kizunaLevel", description = "役職レベル（1〜5）", required = true, in = ParameterIn.PATH) @PathVariable("kizunaLevel") Integer kizunaLevel,
        @Parameter(name = "UpdateRoleLabelRequest", description = "", required = true) @Valid @RequestBody UpdateRoleLabelRequest updateRoleLabelRequest
    );


    /**
     * PUT /api/sections/{sectionId} : 課情報更新
     *
     * @param sectionId 課ID（UUID） (required)
     * @param updateSectionRequest  (required)
     * @return 更新成功 (status code 200)
     *         or 認証エラー（トークン未指定・無効・期限切れ） (status code 401)
     *         or リソースが存在しない (status code 404)
     */
    @Operation(
        operationId = "updateSection",
        summary = "課情報更新",
        tags = { "employees" },
        responses = {
            @ApiResponse(responseCode = "200", description = "更新成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UpdatedAtResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "認証エラー（トークン未指定・無効・期限切れ）", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "リソースが存在しない", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/api/sections/{sectionId}",
        produces = { "application/json" },
        consumes = "application/json"
    )
    
    ResponseEntity<UpdatedAtResponse> updateSection(
        @Parameter(name = "sectionId", description = "課ID（UUID）", required = true, in = ParameterIn.PATH) @PathVariable("sectionId") UUID sectionId,
        @Parameter(name = "UpdateSectionRequest", description = "", required = true) @Valid @RequestBody UpdateSectionRequest updateSectionRequest
    );

}
