/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.12.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.kizunavi.controller;

import com.kizunavi.dto.ErrorResponse;
import com.kizunavi.dto.SimpleStatusResponse;
import com.kizunavi.dto.SubmitAnswerRequest;
import com.kizunavi.dto.SurveyAnswerFormResponse;
import java.util.UUID;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.12.0")
@Validated
@Tag(name = "survey-answer", description = "サーベイ実施画面")
public interface SurveyAnswerApi {

    /**
     * GET /api/survey-answer/{surveyId} : サーベイ回答画面表示
     * employeeIdはJWTから取得。 EMPLOYEESテーブルからkizunaLevel, divisionId, sectionIdを毎回取得（JWTには含めない）。 SURVEY_QUESTIONS.respondentKizunaLevelでkizunaLevelに一致する設問のみ返す。 
     *
     * @param surveyId サーベイID（UUID） (required)
     * @return サーベイ情報と設問一覧 (status code 200)
     *         or 認証エラー（トークン未指定・無効・期限切れ） (status code 401)
     *         or リソースが存在しない (status code 404)
     */
    @Operation(
        operationId = "getSurveyAnswerForm",
        summary = "サーベイ回答画面表示",
        description = "employeeIdはJWTから取得。 EMPLOYEESテーブルからkizunaLevel, divisionId, sectionIdを毎回取得（JWTには含めない）。 SURVEY_QUESTIONS.respondentKizunaLevelでkizunaLevelに一致する設問のみ返す。 ",
        tags = { "survey-answer" },
        responses = {
            @ApiResponse(responseCode = "200", description = "サーベイ情報と設問一覧", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SurveyAnswerFormResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "認証エラー（トークン未指定・無効・期限切れ）", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "リソースが存在しない", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/survey-answer/{surveyId}",
        produces = { "application/json" }
    )
    
    ResponseEntity<SurveyAnswerFormResponse> getSurveyAnswerForm(
        @Parameter(name = "surveyId", description = "サーベイID（UUID）", required = true, in = ParameterIn.PATH) @PathVariable("surveyId") UUID surveyId
    );


    /**
     * POST /api/survey-answer/{surveyId} : サーベイ回答送信
     * employeeIdはJWTから取得。 【バリデーション】answerValueは1〜7の整数のみ許可。範囲外の場合は400エラー。 【二重送信防止】SURVEY_ANSWER_SESSIONS.answeredAt IS NOT NULLの場合は409エラー。 
     *
     * @param surveyId サーベイID（UUID） (required)
     * @param submitAnswerRequest  (required)
     * @return 回答送信成功 (status code 200)
     *         or リクエストパラメータ不正 (status code 400)
     *         or 認証エラー（トークン未指定・無効・期限切れ） (status code 401)
     *         or 回答済み（二重送信） (status code 409)
     */
    @Operation(
        operationId = "submitSurveyAnswer",
        summary = "サーベイ回答送信",
        description = "employeeIdはJWTから取得。 【バリデーション】answerValueは1〜7の整数のみ許可。範囲外の場合は400エラー。 【二重送信防止】SURVEY_ANSWER_SESSIONS.answeredAt IS NOT NULLの場合は409エラー。 ",
        tags = { "survey-answer" },
        responses = {
            @ApiResponse(responseCode = "200", description = "回答送信成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SimpleStatusResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "リクエストパラメータ不正", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "認証エラー（トークン未指定・無効・期限切れ）", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "回答済み（二重送信）", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/survey-answer/{surveyId}",
        produces = { "application/json" },
        consumes = "application/json"
    )
    
    ResponseEntity<SimpleStatusResponse> submitSurveyAnswer(
        @Parameter(name = "surveyId", description = "サーベイID（UUID）", required = true, in = ParameterIn.PATH) @PathVariable("surveyId") UUID surveyId,
        @Parameter(name = "SubmitAnswerRequest", description = "", required = true) @Valid @RequestBody SubmitAnswerRequest submitAnswerRequest
    );

}
