/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.12.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.kizunavi.controller;

import com.kizunavi.dto.CreateSurveyRequest;
import com.kizunavi.dto.CreateSurveyResponse;
import com.kizunavi.dto.ErrorResponse;
import com.kizunavi.dto.SurveyDetailListResponse;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.12.0")
@Validated
@Tag(name = "surveys", description = "サーベイ管理画面")
public interface SurveysApi {

    /**
     * POST /api/surveys : 新規サーベイ配信
     * サーベイを作成し、全従業員にメールを配信する。 SURVEY_ANSWER_SESSIONSに全従業員分のセッションをansweredAt&#x3D;NULLで事前登録。 【メールリンクからのアクセス】未ログイン状態でリンクをクリックした場合、ログイン画面にリダイレクトし、ログイン成功後は元のURL（/survey/answer/{surveyId}）に戻すこと。 
     *
     * @param createSurveyRequest  (required)
     * @return サーベイ配信成功 (status code 201)
     *         or 認証エラー（トークン未指定・無効・期限切れ） (status code 401)
     */
    @Operation(
        operationId = "createSurvey",
        summary = "新規サーベイ配信",
        description = "サーベイを作成し、全従業員にメールを配信する。 SURVEY_ANSWER_SESSIONSに全従業員分のセッションをansweredAt=NULLで事前登録。 【メールリンクからのアクセス】未ログイン状態でリンクをクリックした場合、ログイン画面にリダイレクトし、ログイン成功後は元のURL（/survey/answer/{surveyId}）に戻すこと。 ",
        tags = { "surveys" },
        responses = {
            @ApiResponse(responseCode = "201", description = "サーベイ配信成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CreateSurveyResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "認証エラー（トークン未指定・無効・期限切れ）", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/surveys",
        produces = { "application/json" },
        consumes = "application/json"
    )
    
    ResponseEntity<CreateSurveyResponse> createSurvey(
        @Parameter(name = "CreateSurveyRequest", description = "", required = true) @Valid @RequestBody CreateSurveyRequest createSurveyRequest
    );


    /**
     * GET /api/surveys : サーベイ一覧取得
     * customerIdはJWTから取得。createdAt降順で返却。 ※従業員が多い場合は将来的にrespondentsを別APIに分離を検討（2026/05/13） 
     *
     * @return サーベイ一覧 (status code 200)
     *         or 認証エラー（トークン未指定・無効・期限切れ） (status code 401)
     */
    @Operation(
        operationId = "getSurveys",
        summary = "サーベイ一覧取得",
        description = "customerIdはJWTから取得。createdAt降順で返却。 ※従業員が多い場合は将来的にrespondentsを別APIに分離を検討（2026/05/13） ",
        tags = { "surveys" },
        responses = {
            @ApiResponse(responseCode = "200", description = "サーベイ一覧", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SurveyDetailListResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "認証エラー（トークン未指定・無効・期限切れ）", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/surveys",
        produces = { "application/json" }
    )
    
    ResponseEntity<SurveyDetailListResponse> getSurveys(
        
    );

}
